### ISSUE TITLE
Creation of the collection video

### ISSUE THREAD

**Issue by andreaaraldo** [mora-resource-allocation-edge-cloud/mora#1]
The code that is supposed to create the collection `video` into the mongo DB is commented
(see [this line](https://github.com/mora-resource-allocation-edge-cloud/videomanagement/blob/a1934318e5c1e125cb7751bad836dd969a8c873b/src/main/java/com/arenalocastro/videomanagement/ApplicationConfiguration.java#L92))

Why?

Does it mean that such a collection is created somewhere else? Where?

Moreover, we see that in the cloud node the collection `video` is created in the Cloud, because in the Cloud we can enter the DB and visualize that there is actually the collection video. But we do not manage to see which part of the code creates it, so for us it is a bit of magic this collection `video` appears. We were expecting it was created into the function `setCollection(..)`, even for the cloud node, but we see it is not the case.

The question is: which part of the code creates collection `video` in the cloud node?

**Comment by aleskandro** [comment]
Hi Andrea, that code should not be needed in the cloud variant. That was needed in the Edge variant (see the if statement at line 88). In particular, the edge variant need a capped collection and, by now, this capped collection is created outside the code of the VMS during the deployment. 

However, the creation of the capped collection during the deployment has to be reviewed after the implementation of the vanilla kubernetes / minikube compatibility: going to create an issue about this.

Please, close this issue if my reply is exhaustive.

**Comment by andreaaraldo** [comment]
Thanks
