### ISSUE TITLE
Configure the dns in cloud scenario

### ISSUE THREAD

**Issue by Maya-kassis** [mora-resource-allocation-edge-cloud/mora#18]
About the DNS problem. As already discussed in the related issue on Github, solution is not to use a static mapping of the IP-Address pairing (within the deployment files) but to provide the right hostname in the values.yaml file that you are using as "custom settings " for your deployment. It has to be cloudmora.eu if you are deploying the edge version. Moreover, on Postman you have to provide a resolvable name that will route to the Ingress of the cluster (i.e., the minikube ip).I note that my choice of using that example hostname is not understood by everyone, so probably it is lack of documentation or my way of elaborate it. As Hakim suggests, and to clarify the example:The ingress object of kubernetes will listen at a given tcp port for http connection (let's say port 80). 

Let's assume that the IP Address of the Minikube VM is 192.168.99.23.If you make a HTTP request to 192.168.99.23:80 (curl 192.168.99.23 ) you will get the default response by the nginx container that handle ingress objects, deployed as an internal component of the kube-system namespace of minikube's kubernetes.Any ingress object consist, at least of:

    A hostname
    A set of rules that map URIs to k8s services objects

If you make a request as above setting the Host   header to a given hostname (let's say mydomain.mytld ) the nginx controller will look in the available ingress objects "applied" to  the cluster and, if one of them reports the hostname mydomain.tld, it will try to lookup the rule that matches the uri of the request in order to forward the request to the backend service associated with the rule.
So, if we have an ingress object like

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  -  host: mydomain.tld
     http:
      paths:
      - path: /myuri
        pathType: Prefix
        backend:
          service:
            name: the-service-handling-myuri
            port:
              number: 8080

And we make the following request:
curl -H "Host: mydomain.tld" 192.168.99.23/myuri?myarg=myvalueNginx will:

    Find the minimal-ingress object because the Host header is set to mydomain.tld
    Find in the paths list the one that starts with /myuri, since myuri is the path provided in the request itself
    Forward the request to the service the-service-handling-myuri at port 8080

The cloud-vms-1.particles.dieei.unict.it is an internal hostname that is available within the internal cluster at the university of catania. You will not solve anytime that host if not by the manual mapping suggested by hakim.However, you can set your hostname for the video-service application like my-youtube.localhost , set it in the values.yaml file at the cloudURL key dedicated for this job, and finally let your workstation/client solve that hostname to the ip address of minikube appending the following line to its /etc/hosts file

192.168.99.23 my-youtube.localhost

Essentially, this solution allows anyone to deploy its video application mapping it to the domain they own.Alternatively, if we buy a dns zone for a given domain name, e.g., maya-youtube.com, and you also have a public ip at which the nginx controller of your kubernetes cluster is listening to, you can set

    a dns record .maya-youtube.com A $YOUR_CLUSTER_IP
    the cloudUrl to maya-youtube.com

In this way, you have finally deployed the video application anywhere making it public availble for anyone in the worldIn particular, changing this hostname will lead us to use multiple deployments of the same application simulating different video-service providers (edited) 
6:18
PS: the Host header is set by any http client if you use the hostname rather thant its associated ip address in the URL
6:19
so if we can solve google.com to 5.23.45.99 you will make a request to this IP with the host header set to google.com and google will handle it showing the home page of its search engine (a lot simplified obviously)

**Comment by Maya-kassis** [comment]
Let’s consider the cloud scenario only for this issue.

As I understand, no need to explicitly define the internal names cloud-vms-1.master.particles.dieei.unict.it  &  edge-vp-1.master.particles.dieei.unict.it


I only need to change the cloudURL in values.yaml to be for example: videoService.AIDY (on machine 1)
On the client side, I have to modify the etc/hosts to be
(IP of the machine 1)  videoService.AIDY 

But then if I want to add a user from external, should I still use the link http://cloud-vms-1.master.particles.dieei.unict.it/vms/register?

Plus, where should we mention cloudmora.eu?

I have a very basic question, as I understand the Ingress and Ingress controller are related to the cluster itself, but is it running on your side in Catania university in case of cloud scenario or should I have to create it also on my side?

**Comment by aleskandro** [comment]
the CloudURL has to be `cloudmora.eu` to use our service at university of catania.

The ingress has to run in Kubernetes. 

For minikube, you have to enable it; In the openshift at university of catania, we have "similar" objects for the "cloud version".

The edge version that will run in Kube5G has to run an Ingress Controller/Plugin.

As an example, kubespray documentation has some info on deploying the Ingress plugin of your choice: https://kubespray.io/#/docs/ingress_controller/ingress_nginx

**Comment by aleskandro** [comment]
The dns is now configured "publicly".

cloudmora.eu is the cloud variant running at the university of catania.

edge.cloudmora.eu is bound to the IP @Maya-kassis  provided me. In this way, we should not have anymore need to figure out dns configuration stuff. Any client/pod which has access to the internet will be able to solve both the names.
