### ISSUE TITLE
Fix documentation: Building without Minikube 

### ISSUE THREAD

**Issue by Cicero1996** [mora-resource-allocation-edge-cloud/mora#22]
<img width="972" alt="Schermata 2021-07-28 alle 12 15 28" src="https://user-images.githubusercontent.com/58262137/127305985-f2aa6eb8-ebf9-4765-b7ba-5af16185e416.png">

**NOT** cd helm/docker/gateway **but:**
cd ..
cd /deployment/docker/gateway
docker build -t aleskandro/video-server:cloud-gateway -f Dockerfile . 
cd ..
cd load-balancer
docker build -t aleskandro/video-server:edge-lb -f Dockerfile .

**Comment by aleskandro** [comment]
Thank you @Cicero1996, fixed. Going to give you contributor permissions
