### ISSUE TITLE
Fix file 04-mongodb.yaml on path  vp-cloud/templates/

### ISSUE THREAD

**Issue by Cicero1996** [mora-resource-allocation-edge-cloud/mora#27]
There is an error in the file vp-cloud/templates/04-mongodb.yaml 
<img width="447" alt="Schermata 2021-08-08 alle 18 13 22" src="https://user-images.githubusercontent.com/58262137/128638431-edcb591c-f6e4-4cab-9cef-b6fcc85b99f8.png">

It is not possible to deploy the application:
<img width="1572" alt="Schermata 2021-08-08 alle 18 12 31" src="https://user-images.githubusercontent.com/58262137/128638402-8cf42416-afd3-4a6c-9ad4-a356bf88ead8.png">

**Comment by Cicero1996** [comment]
if eq .Values.isOpenShift true without ""

**Comment by aleskandro** [comment]
Hi @Cicero1996, checkout the latest version of the application. 
There are new examples at deployment/variants/examples.

Please, feel free to fix your self this kind of bugs. 

isOpenShift is currently a string. Somewhere it has been used as bool. A todo in the main values.yaml is already set to assess in the future the "conversion" to boolean

**Comment by aleskandro** [comment]
For the moment, please, keep it as a string.

**Comment by aleskandro** [comment]
```yaml

# If you are deploying on OpenShift, keep this true (Note, it's a string)
# TODO make isOpenshift bool
isOpenShift: "true"

```

**Comment by aleskandro** [comment]
@Cicero1996 When you start edits in a repository, use a separate branch and make us know that it is there by opening a pull request

**Comment by aleskandro** [comment]
Closing this since it's already fixed in the deveolpment branch.

https://github.com/mora-resource-allocation-edge-cloud/deployment/blob/development/variants/values.cache-variant.yaml

deployment/variants/values.cache-variant.yaml
```
isOpenShift: "false"
isMinikube: true
```
