### ISSUE TITLE
Error during the exe the deploy of the application with Helm

### ISSUE THREAD

**Issue by Cicero1996** [mora-resource-allocation-edge-cloud/mora#29]
During the exe of the command helm:
<img width="1176" alt="Schermata 2021-08-18 alle 16 49 44" src="https://user-images.githubusercontent.com/58262137/130088087-00bfae7a-6f1c-40d3-9fa8-cfea9777e603.png">

We need to add the graph of the values.yaml file a new key: 

Insert into values.yaml:
<img width="190" alt="Schermata 2021-08-19 alle 16 39 57" src="https://user-images.githubusercontent.com/58262137/130088589-fc21369c-974c-4353-8c6f-073dcb39a27f.png">

**Also vp-cloud/templates/NOTES.txt,**  we need to add the graph of the values.yaml file a new key: 
<img width="995" alt="Schermata 2021-08-19 alle 16 43 31" src="https://user-images.githubusercontent.com/58262137/130089253-d9a928eb-2376-4fe3-9817-e69b749d43ea.png">

Insert into values.yaml:
<img width="315" alt="Schermata 2021-08-19 alle 16 45 22" src="https://user-images.githubusercontent.com/58262137/130089523-536d420d-8aea-4db5-8d84-b45524f79179.png">

Ask if the insertion of these portions of code into values.yaml is correct.

For finally, this error:
Error: template: vp-cloud/templates/02-videomanagement.yml:25:17: executing "vp-cloud/templates/02-videomanagement.yml" at <eq .Values.noDNSServerForCloud true>: error calling eq: incompatible types for comparison

Also, insert a new key noDNSServerForCloud into a values.yaml

**Comment by aleskandro** [comment]
Hi @Cicero1996 are you sure you are using the last updated version of the deployment repository? Branch development.

All these issues should already be fixed in the head of development branch.

```
cd deployment
git checkout development
git pull
```

**Comment by Cicero1996** [comment]
Hey Alessandro,, ho risolto il problema della pull del progetto. Tuttavia, 

Eseguendo il comando: $ helm install vp-cloud -f variants/examples/values.minikube-cloud.yaml --generate-name --disable-openapi-validation

W0823 23:25:36.552529 2997292 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Error: Deployment.apps "mongodb" is invalid: [spec.template.spec.volumes[0].persistentVolumeClaim: Forbidden: may not specify more than 1 volume type, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "data”]

Hai suggerimenti in merito all’errore?

**Comment by Cicero1996** [comment]
EXE this command: $ helm install vp-cloud -f variants/examples/values.minikube-cloud.yaml --generate-name --disable-openapi-validation

Error: Deployment.apps "mongodb" is invalid: [spec.template.spec.volumes[0].persistentVolumeClaim: Forbidden: may not specify more than 1 volume type, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "data”]



I'm not deploying the project correctly.

**Comment by aleskandro** [comment]
Hi @Cicero1996, can you try now?
