### ISSUE TITLE
Clarification about isOpenShift

### ISSUE THREAD

**Issue by andreaaraldo** [mora-resource-allocation-edge-cloud/mora#5]
From [this line](https://github.com/mora-resource-allocation-edge-cloud/mora/blob/minikubebranch/README.md#isopenshift) below, it seems that OpenShift is an alternative to Kubernates. Instead, it seems that OpenShift does use Kubernates (see [wikipedia page](https://en.wikipedia.org/wiki/OpenShift)). So, it is not clear when we should put isOpenShift true or false.
Could you please clarify directly in the documentation (the minikube branch) (no need to reply directly here)

Thx

**Comment by aleskandro** [comment]
Hi Andrea, yes, OpenShift is based on Kubernetes. the isOpenShift flag is used to tell helm to deploy or not objects specific to OpenShift (routes, etc...)
