### ISSUE TITLE
DNS resolution and Clients/Edge deployment resolving the Cloud Variant hostname

### ISSUE THREAD

**Issue by aleskandro** [mora-resource-allocation-edge-cloud/mora#6]
Hi @zazim13, as anticipated in the meeting, I was suggesting to replace the URL (cloud-vms.1.master.particles.dieei.unict.it) with the public available one: cloudmora[dot]eu.

The original one is the domain name that can be resolved only within the University of Catania cluster through an internal DNS server.
Instead, cloudmora.eu, is registered through public DNS Nameservers. I can also provide  (in pvt) credentials to add other rules in the zone (e.g., for the dash player or the metrics collector).

As we're going to use the cloud variant deployed at University of Catania's cluster, just using it would be enough.

As for documentation purposes, we shall suggest to use a DNS server in order to make both the clients and the internal containers able to resolve the cloud web service hostname. This is the recommended way.

### Clients

Set properly the clients' hosts file (i.e., /etc/hosts for *nix operative systems)  with a line like the following:
```
$IP_ADDRESS $CLOUD_VMS_DOMAIN_NAME
```
where
- $IP_ADDRESS is the ip of the machine executing the ingress container and
- $CLOUD_VMS_DOMAIN_NAME is the domain name of the cloud variant as specified in the `values.yaml` file of the Helm template

This will make the cloud domain name available for the clients.

### Let the (edge) containers resolve the Cloud variant services

To let the Edge variants' containers able to both download videos from the Cloud variant  and balance the traffic between the Edge containers and the cloud containers, with no DNS server available, a user should provide the IP address to fulfill the hostAliases as you did.

If we want to allow users also this second way we should do something like:

1. add a `noDNSServerForCloud` field in the `values.yaml` file. The value of this field has to be `false` by default.
2. add a `CloudIP` to the `routes` map in the `values.yaml` file. The default value has to be the empty string
3. In the deployments that need this mapping, the load balancer and the vms, we have to add the hostAliases as you did, but only if `noDNSServerForCloud` is set to `true`:

For instance, at rows around https://github.com/mora-resource-allocation-edge-cloud/deployment/blob/fa93ab2076c9b9a9c49617ca368db832fc70cc85/vp-cloud/templates/02-videomanagement.yml#L25,
we should add something like:

```yaml
{{- if eq .Values.noDNSServerForCloud true }}
hostAliases:
[......]
{{- end }}
```

Do we really want to pursue this way? (@andreaaraldo).
I don't think it's a high-priority and I think it's not so helpful. 

Usually, people deploying this kind of software are able to configure the first solution. I have never seen software of this kind not being related/coupled to hostnames in the way we already have out of the box (no IPs). 

I usually see the requirement of setting properly the hostnames where needed.

**Comment by aleskandro** [comment]
@zazim13 shall we close this issue?

**Comment by zazim13** [comment]
@aleskandro There is only documentation left. Should I close it now ?

**Comment by aleskandro** [comment]
Ok, you can proceed to close it after documentation will be available.
